---
services:
  rdesktop:
    image: lscr.io/linuxserver/rdesktop:arch-kde
    container_name: archKDE
    hostname: archKDE
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - ./config:/config #optional
      - /mnt/Vms:/mnt/Data
    ports:
      - 3389:3389
      - 6022:22
    devices:
      - /dev/dri:/dev/dri
    shm_size: "2gb"
    restart: unless-stopped
