version: "3"
services:
  win10:
    image: dockurr/windows
    container_name: window10
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    environment:
      RAM_SIZE: "5G"
      CPU_CORES: "8"
      DISK_SIZE: "128G"
      MANUAL: "Y"
      VERSION: "custom.iso"
    device_cgroup_rules:
      - 'c *:* rwm'
    volumes:
      - /home/mrbhola/.docker/win10/storage:/storage
    stop_grace_period: 2m
    restart: on-failure
