version: "3"
services:
  winxp:
    image: dockurr/windows
    container_name: winxp
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8009:8006
      - 3380:3389/tcp
      - 3380:3389/udp
    environment:
      RAM_SIZE: "2G"
      CPU_CORES: "4"
      DISK_SIZE: "128G"
      VERSION: "winxp"
    device_cgroup_rules:
      - 'c *:* rwm'
    volumes:
      - /home/mrbhola/.docker/winxp/storage:/storage
    stop_grace_period: 2m
    restart: none
